//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kysect.Shreks.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kysect.Shreks.Common.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have permission for changing submission..
        /// </summary>
        internal static string DoesNotHavePermissionForChangeSubmission {
            get {
                return ResourceManager.GetString("DoesNotHavePermissionForChangeSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing {0} command..
        /// </summary>
        internal static string DomainExceptionWhileProcessingUserCommand {
            get {
                return ResourceManager.GetString("DomainExceptionWhileProcessingUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse user command. Ensure that all arguments are correct or call /help..
        /// </summary>
        internal static string FailedToParseUserCommand {
            get {
                return ResourceManager.GetString("FailedToParseUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while processing command. Contact support for details..
        /// </summary>
        internal static string InternalExceptionWhileProcessingUserCommand {
            get {
                return ResourceManager.GetString("InternalExceptionWhileProcessingUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission activated successfully..
        /// </summary>
        internal static string SubmissionActivatedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission created.\n{0}.
        /// </summary>
        internal static string SubmissionCreated {
            get {
                return ResourceManager.GetString("SubmissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission deactivated successfully..
        /// </summary>
        internal static string SubmissionDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission deleted successfully..
        /// </summary>
        internal static string SubmissionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission marked as reviewed..
        /// </summary>
        internal static string SubmissionMarkedAsReviewed {
            get {
                return ResourceManager.GetString("SubmissionMarkedAsReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission rated.\n{0}.
        /// </summary>
        internal static string SubmissionRated {
            get {
                return ResourceManager.GetString("SubmissionRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission updated.\n{0}.
        /// </summary>
        internal static string SubmissionUpdated {
            get {
                return ResourceManager.GetString("SubmissionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to activate this submission..
        /// </summary>
        internal static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to activate this submission..
        /// </summary>
        internal static string UserDoesNotHavePermissionForActivateSubmission {
            get {
                return ResourceManager.GetString("UserDoesNotHavePermissionForActivateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find user with github {0}. All users should be registered before submitting tasks..
        /// </summary>
        internal static string UserNotFoundByGithubUsername {
            get {
                return ResourceManager.GetString("UserNotFoundByGithubUsername", resourceCulture);
            }
        }
    }
}
