//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kysect.Shreks.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kysect.Shreks.Common.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AssignmentNotFound {
            get {
                return ResourceManager.GetString("AssignmentNotFound", resourceCulture);
            }
        }
        
        internal static string ClosePullRequestWithUnratedSubmission {
            get {
                return ResourceManager.GetString("ClosePullRequestWithUnratedSubmission", resourceCulture);
            }
        }
        
        internal static string DoesNotHavePermissionForChangeSubmission {
            get {
                return ResourceManager.GetString("DoesNotHavePermissionForChangeSubmission", resourceCulture);
            }
        }
        
        internal static string DomainExceptionWhileProcessingUserCommand {
            get {
                return ResourceManager.GetString("DomainExceptionWhileProcessingUserCommand", resourceCulture);
            }
        }
        
        internal static string FailedToParseUserCommand {
            get {
                return ResourceManager.GetString("FailedToParseUserCommand", resourceCulture);
            }
        }
        
        internal static string InternalExceptionWhileProcessingUserCommand {
            get {
                return ResourceManager.GetString("InternalExceptionWhileProcessingUserCommand", resourceCulture);
            }
        }
        
        internal static string MentorMergeUnratedSubmission {
            get {
                return ResourceManager.GetString("MentorMergeUnratedSubmission", resourceCulture);
            }
        }
        
        internal static string MergePullRequestAndMarkAsCompleted {
            get {
                return ResourceManager.GetString("MergePullRequestAndMarkAsCompleted", resourceCulture);
            }
        }
        
        internal static string MergePullRequestWithoutRate {
            get {
                return ResourceManager.GetString("MergePullRequestWithoutRate", resourceCulture);
            }
        }
        
        internal static string NoSubmissionInPullRequest {
            get {
                return ResourceManager.GetString("NoSubmissionInPullRequest", resourceCulture);
            }
        }
        
        internal static string NoUnratedSubmissionInPullRequest {
            get {
                return ResourceManager.GetString("NoUnratedSubmissionInPullRequest", resourceCulture);
            }
        }
        
        internal static string RepositoryAssignedToAnotherUserClosePullRequest {
            get {
                return ResourceManager.GetString("RepositoryAssignedToAnotherUserClosePullRequest", resourceCulture);
            }
        }
        
        internal static string RepositoryAssignedToAnotherUserSubmissionUpdated {
            get {
                return ResourceManager.GetString("RepositoryAssignedToAnotherUserSubmissionUpdated", resourceCulture);
            }
        }
        
        internal static string ReviewRatedSubmission {
            get {
                return ResourceManager.GetString("ReviewRatedSubmission", resourceCulture);
            }
        }
        
        internal static string ReviewWithoutRate {
            get {
                return ResourceManager.GetString("ReviewWithoutRate", resourceCulture);
            }
        }
        
        internal static string SubjectCourseForOrganizationNotFound {
            get {
                return ResourceManager.GetString("SubjectCourseForOrganizationNotFound", resourceCulture);
            }
        }
        
        internal static string SubmissionActivatedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionActivatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string SubmissionCreated {
            get {
                return ResourceManager.GetString("SubmissionCreated", resourceCulture);
            }
        }
        
        internal static string SubmissionDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string SubmissionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionDeletedSuccessfully", resourceCulture);
            }
        }
        
        internal static string SubmissionMarkAsReviewedAndNeedDefense {
            get {
                return ResourceManager.GetString("SubmissionMarkAsReviewedAndNeedDefense", resourceCulture);
            }
        }
        
        internal static string SubmissionMarkedAsReviewed {
            get {
                return ResourceManager.GetString("SubmissionMarkedAsReviewed", resourceCulture);
            }
        }
        
        internal static string SubmissionRated {
            get {
                return ResourceManager.GetString("SubmissionRated", resourceCulture);
            }
        }
        
        internal static string SubmissionUpdated {
            get {
                return ResourceManager.GetString("SubmissionUpdated", resourceCulture);
            }
        }
        
        internal static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        internal static string UserDoesNotHavePermissionForActivateSubmission {
            get {
                return ResourceManager.GetString("UserDoesNotHavePermissionForActivateSubmission", resourceCulture);
            }
        }
        
        internal static string UserNotFoundByGithubUsername {
            get {
                return ResourceManager.GetString("UserNotFoundByGithubUsername", resourceCulture);
            }
        }
        
        internal static string UserNotFoundInSubjectCourse {
            get {
                return ResourceManager.GetString("UserNotFoundInSubjectCourse", resourceCulture);
            }
        }
        
        internal static string StudentGroupAssignmentMismatch {
            get {
                return ResourceManager.GetString("StudentGroupAssignmentMismatch", resourceCulture);
            }
        }
    }
}
