//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kysect.Shreks.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kysect.Shreks.Common.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment with branch name &apos;{0}&apos; for subject course &apos;{1}&apos; was not found. Ensure that branch name is correct. Available assignments: {2}..
        /// </summary>
        internal static string AssignmentNotFound {
            get {
                return ResourceManager.GetString("AssignmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: pull request closed and mark as inactive. Submission {0} will not be rated..
        /// </summary>
        internal static string ClosePullRequestWithUnratedSubmission {
            get {
                return ResourceManager.GetString("ClosePullRequestWithUnratedSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have permission for changing submission..
        /// </summary>
        internal static string DoesNotHavePermissionForChangeSubmission {
            get {
                return ResourceManager.GetString("DoesNotHavePermissionForChangeSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing {0} command..
        /// </summary>
        internal static string DomainExceptionWhileProcessingUserCommand {
            get {
                return ResourceManager.GetString("DomainExceptionWhileProcessingUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse user command. Ensure that all arguments are correct or call /help..
        /// </summary>
        internal static string FailedToParseUserCommand {
            get {
                return ResourceManager.GetString("FailedToParseUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while processing command. Contact support for details..
        /// </summary>
        internal static string InternalExceptionWhileProcessingUserCommand {
            get {
                return ResourceManager.GetString("InternalExceptionWhileProcessingUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission merged by mentor and will be rated with 100..
        /// </summary>
        internal static string MentorMergeUnratedSubmission {
            get {
                return ResourceManager.GetString("MentorMergeUnratedSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission merged by mentor and mark as Completed..
        /// </summary>
        internal static string MergePullRequestAndMarkAsCompleted {
            get {
                return ResourceManager.GetString("MergePullRequestAndMarkAsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: pull request was merged, but submission {0} is not yet rated..
        /// </summary>
        internal static string MergePullRequestWithoutRate {
            get {
                return ResourceManager.GetString("MergePullRequestWithoutRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submission in pull request  {0}..
        /// </summary>
        internal static string NoSubmissionInPullRequest {
            get {
                return ResourceManager.GetString("NoSubmissionInPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unrated submission in pull request  {0}..
        /// </summary>
        internal static string NoUnratedSubmissionInPullRequest {
            get {
                return ResourceManager.GetString("NoUnratedSubmissionInPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository {0} is assigned to another student. User {1} does not have permission here. Close this PR and open new with correct account..
        /// </summary>
        internal static string RepositoryAssignedToAnotherUserClosePullRequest {
            get {
                return ResourceManager.GetString("RepositoryAssignedToAnotherUserClosePullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository {0} is assigned to another student. Do not use {1} account for this repository. Submission date will be updated..
        /// </summary>
        internal static string RepositoryAssignedToAnotherUserSubmissionUpdated {
            get {
                return ResourceManager.GetString("RepositoryAssignedToAnotherUserSubmissionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is already rated with {0} points. If you want to change it, please use /update command..
        /// </summary>
        internal static string ReviewRatedSubmission {
            get {
                return ResourceManager.GetString("ReviewRatedSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review proceeded, but submission is not yet rated and still will be presented in queue..
        /// </summary>
        internal static string ReviewWithoutRate {
            get {
                return ResourceManager.GetString("ReviewWithoutRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectCourse with organization {0} not found..
        /// </summary>
        internal static string SubjectCourseForOrganizationNotFound {
            get {
                return ResourceManager.GetString("SubjectCourseForOrganizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission activated successfully..
        /// </summary>
        internal static string SubmissionActivatedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission created.
        ///{0}.
        /// </summary>
        internal static string SubmissionCreated {
            get {
                return ResourceManager.GetString("SubmissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission deactivated successfully..
        /// </summary>
        internal static string SubmissionDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission deleted successfully..
        /// </summary>
        internal static string SubmissionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SubmissionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission state changed to reviewed. Mentor should merge PR after defense..
        /// </summary>
        internal static string SubmissionMarkAsReviewedAndNeedDefense {
            get {
                return ResourceManager.GetString("SubmissionMarkAsReviewedAndNeedDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission marked as reviewed..
        /// </summary>
        internal static string SubmissionMarkedAsReviewed {
            get {
                return ResourceManager.GetString("SubmissionMarkedAsReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission rated.
        ///{0}.
        /// </summary>
        internal static string SubmissionRated {
            get {
                return ResourceManager.GetString("SubmissionRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission updated.
        ///{0}.
        /// </summary>
        internal static string SubmissionUpdated {
            get {
                return ResourceManager.GetString("SubmissionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to do this action..
        /// </summary>
        internal static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to activate this submission..
        /// </summary>
        internal static string UserDoesNotHavePermissionForActivateSubmission {
            get {
                return ResourceManager.GetString("UserDoesNotHavePermissionForActivateSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find user with github {0}. All users should be registered before submitting tasks..
        /// </summary>
        internal static string UserNotFoundByGithubUsername {
            get {
                return ResourceManager.GetString("UserNotFoundByGithubUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id {0} not found or have no permissions to create submission in course {1}..
        /// </summary>
        internal static string UserNotFoundInSubjectCourse {
            get {
                return ResourceManager.GetString("UserNotFoundInSubjectCourse", resourceCulture);
            }
        }
    }
}
