@startuml Subject lesson

actor Student
actor Teacher

loop 
    Student --> Github : Создаёт репозиторий
    Student --> Github : Загружает решение по работе
    Github --> СУФ : Отправляет информацию о добавлении работы
    СУФ --> СУФ : Добавляет студента в очередь
    СУФ --> GoogleTable : Обновляет очередь

    Teacher --> GoogleTable : Смотрит следующего в очереди студента
    GoogleTable --> Teacher : Данные о последнем студенте в очереди

    Teacher --> Student : Проводит защиту

    alt Нужны правки
        Teacher --> Github : Оставляет команду выставения баллов
        Github --> СУФ : Отправляет событие о новой комментарии
        СУФ --> СУФ : Проставляет баллы студентам
        СУФ --> GoogleTable : Обновление баллов
    else
        Teacher --> Github : Оставляет замечания и текущие баллы
        Github --> СУФ : Отправляет событие о новой комментарии
        СУФ --> СУФ : Проставляет баллы студентам
        СУФ --> GoogleTable : Обновление баллов
        Student --> Github : Загрузка работы
        Github --> СУФ : Отправка события о добавлении работы
        СУФ --> СУФ : Добавляет студента в очередь

        
    end
end

@enduml