@startuml Pull request creatin

actor User

User -> Github : Create pull request
Github -> WebhookEventProcessor : Call /api/github/webhooks

WebhookEventProcessor -> Shreks : CreateSubmission(githubUsername, pullRequestLink)
Shreks -> Shreks : GetStudentByUsername(githubUsername)
Shreks -> Shreks : GetStudentAssignment(student, assignmentShortName)
Shreks -> DatabaseContext : CreateSubmission(submission)

Shreks -> WebhookEventProcessor : Created submission
WebhookEventProcessor -> Github : Send comment

@enduml